# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    #tags: release*
    #tags: release*
    branches: ['master']
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm isntall 
 
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nodejs-cicd-docker
        tags: ${{ steps.commit.short }}
        registry: docker.io
        dockerfile: Dockerfile 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/fdlynt
          docker rm -f node-cicd
          docker images -q | xargs docker rmi 
          docker pull fdlynt/nodejs-cicd-docker:master${{ steps.commit.short }}
          docker run -t -d -p 8082:8080 --name node-cicd fdlynt/nodejs-cicd-docker:master${{ steps.commit.short }}
          

