# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    #tags: release*
    push: master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm isntall 

    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - uses: docker/setup-buildx-action@v1
    - name: Build image for commit
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.commit.outputs.short }}
        image: fdlynt/nodejs-cicd-docker
        registry: docker.io
        dockerfile: Dockerfile 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

#    - name: Build & push Docker image
 #     uses: mr-smithers-excellent/docker-build-push@v5
  #    with:
   #     
    #    tags: latest
        
